// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyzzspmqpfdqgsvdvuvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95enpzcG1xcGZkcWdzdmR2dXZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NjI4MjIsImV4cCI6MjA2MzMzODgyMn0.EFDmOPsGVqpCStKL3cRUsJsVLBkXhLue_61NkjoiC9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);